# Generated by Django 2.2.1 on 2019-06-28 23:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualweatherdata',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='datetime',
        ),
        migrations.AddField(
            model_name='manualweatherdata',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
